In [4]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectPercentile


# Naive Bayes

In [11]:
data = pd.read_csv('C:\\Users\\Admin\\Desktop\\SARLAKG\\spam.csv',encoding='latin-1')

In [12]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [13]:
data.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [15]:
data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'], axis=1,inplace=True)

In [18]:
data1 = data['v1']
data.shape

(5572, 2)

In [21]:
X_train, X_test,y_train, y_test = train_test_split(data.v2,data.v1,test_size=0.3)

In [24]:
y_test.shape

(1672,)

In [25]:
X_train.head()

4197    Want to funk up ur fone with a weekly new tone...
1282    Ever green quote ever told by Jerry in cartoon...
5228    PRIVATE! Your 2003 Account Statement for <fone...
1673    Monthly password for wap. mobsi.com is 391784....
4749    If you're still up, maybe leave the credit car...
Name: v2, dtype: object

In [26]:
vectorizer = TfidfVectorizer()

In [27]:
X_train_transformed = vectorizer.fit_transform(X_train)
X_test_transformed = vectorizer.transform(X_test)

In [28]:
features_names = vectorizer.get_feature_names()

In [31]:
len(features_names)

7143

In [32]:
selector = SelectPercentile(percentile=5)
selector.fit(X_train_transformed, y_train)
X_train_transformed = selector.transform(X_train_transformed).toarray()
X_test_transformed = selector.transform(X_test_transformed).toarray()



In [33]:
X_train_transformed 

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.10410496,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

## Applying Naive Bayes

In [39]:
m1 = GaussianNB()

m1.fit(X_train_transformed,y_train)
y_predict = m1.predict(X_test_transformed)
y_predict # Predicted Value
y_test # Actual Value
accuracy_score(y_test,y_predict)
#y_predict
#accuracy_score(y_test,y_predict)
np.mean(y_test == y_predict)
confusion_matrix(y_test,y_predict)

array([[1414,   28],
       [  21,  209]], dtype=int64)

In [42]:
1623/1672

0.9706937799043063

In [41]:
y_test.shape

(1672,)

In [43]:
np.mean(y_test == y_predict)

0.97069377990430628

In [44]:
confusion_matrix(y_test,y_predict)

array([[1414,   28],
       [  21,  209]], dtype=int64)

In [33]:
(1435+187)/(1435+187+30+20)

0.9700956937799043

In [45]:
model_bernb = BernoulliNB()

model_bernb.fit(X_train_transformed,y_train)
y_predict = model_bernb.predict(X_test_transformed)


accuracy_score(y_test,y_predict)



0.98385167464114831

In [46]:
model_mulnb = MultinomialNB()

model_mulnb.fit(X_train_transformed,y_train)
y_predict = model_mulnb.predict(X_test_transformed)


accuracy_score(y_test,y_predict)



0.91985645933014359

In [43]:
newEmail = pd.Series('hello how are you')

In [44]:
newEmail

0    hello how are you
dtype: object

In [45]:
newEmail_transformed = vectorizer.transform(newEmail)
newEmail_transformed = selector.transform(newEmail_transformed).toarray()

In [46]:
m1.predict(newEmail_transformed)

array(['ham'],
      dtype='<U4')